### ISSUE TITLE
Material Design 3 Colors and 13 Tones

### ISSUE THREAD

**Issue by thomastthai** [aotearoan/sass-farbig#36]
Thoughts on adapting the code to support Material Design 3? The method is similar to how they pick their colors and 13 tones per color.

**Comment by aotearoan** [comment]
There are no plans to support specific frameworks with this other than [Neon](https://aotearoan.github.io/neon/).

**Comment by thomastthai** [comment]
Thanks for the response. Keep up the awesome work!
